package:
  name: obit
  version: 27JUL20a

source:
  url: http://www.jive.nl/parseltongue/releases/Obit-27JUL20a.tar.gz
  sha256: 8e5c2e2ba814387569d5b545c5f83cf10e38ac98e0b46b451b2229ff94aa7e1d

requirements:
  build:
    - cfitsio
    - glib
    - gsl
    - numpy
    - python
    - setuptools

  run:
    - cfitsio
    - glib
    - gsl
    - numpy
    - python

build:
  number: 0

about:
  home: http://www.cv.nrao.edu/~bcotton/Obit.html
  license: GPLv2+
  license_file: LICENSE
  summary: stripped down version of Obit for use with ParselTongue
