package:
  name: parseltongue
  version: '3.0'

source:
  url: http://www.jive.nl/parseltongue/releases/parseltongue-3.0.tar.gz
  sha256: 3b2c159c105556550776558d97201b7b48c66b9e79863f75d1b382f6e548acc2

requirements:
  build:
    - obit
    - python
    - setuptools

  run:
    - numpy
    - obit
    - python

build:
  number: 0

about:
  home: http://www.jive.eu/jivewiki/doku.php?id=parseltongue:parseltongue
  license: GPLv2+
  license_file: COPYING
  summary: a Python scripting interface for classic AIPS
