package:
  name: cfitsio
  version: '3.410'

source:
  url: http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3410.tar.gz
  sha256: 670c9d0992d99e34fb8e24f0a637b3f306c6c9f9ca084ac8ae82ebf0a1a068a3

build:
  number: 1

test:
  commands:
  - test -f ${PREFIX}/lib/libcfitsio.a    # [not win]
  - test -f ${PREFIX}/lib/libcfitsio.so    # [linux]
  - test -f ${PREFIX}/lib/libcfitsio.dylib    # [osx]
    # - conda inspect linkages -n _test cfitsio  # [linux]

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: custom
  license_file: License.txt
  summary: library of ANSI C routines for reading and writing FITS format data files
